### ISSUE TITLE
Help with controller config for the Anbernic RG351V

### ISSUE THREAD

**Issue by Furaihai** [JeodC/PortMaster-ShipOfHarkinian#1]
I got the port working on my device, but I can't access the menu navigation despite trying every combination of holding X/Y, pressing R1/R2, then pressing X/Y again. 

What parameters can I enter into the soh.gptk file to set the middle F button of my device to bring up the menu instead of L3, and have dpad up/down/left/right act as my c buttons?

Alternatively, could I also set the c buttons with a combination of R2 + analog?

**Comment by JeodC** [comment]
You need to keep X/Y held down when you press R1/R2. The window switching buttons could be mapped differently depending on your device as well. I have no idea how to set the F button--you can try asking around the PortMaster Discord.
