### ISSUE TITLE
Game doesn't load on RG353V

### ISSUE THREAD

**Issue by CynicalDonut** [JeodC/PortMaster-ShipOfHarkinian#4]
Running on ArkOS.  Rotating ship logo will appear and I can interact with the enhancements menu while it's there but once it tries to load into the game itself it hangs until I hit start+select to close it.  Something about failing to load resources, log is attached.
[log.txt](https://github.com/user-attachments/files/16118642/log.txt)

**Comment by JeodC** [comment]
Thanks for the log. Please try getting help at the PortMaster discord.
