### ISSUE TITLE
Additional Controller Options Not Showing 

### ISSUE THREAD

**Issue by KJLambo** [JeodC/PortMaster-ShipOfHarkinian#8]
Went to add in dpad controls for SOH and they are not there. The entire additional controller options dont show.

Device is Anbernic RG35XXSP

**Comment by JeodC** [comment]
![muOS_20241021_1308_0](https://github.com/user-attachments/assets/d7326490-27b8-41f6-a73c-21a9a622d639)
It's at the bottom of controller configuration. If you can't scroll down that far try pressing A to expand Miscellaneous Controls and then try scrolling down again.

**Comment by JeodC** [comment]
You can also open your `imgui.ini` file and modify the following:
```
[Window][###sohControllerConfigWindowV1]
Pos=30,30
Size=387,300
Collapsed=0
```
